### ISSUE TITLE
Interactive lessons are not working

### ISSUE THREAD

**Issue by gabrielperales** [nwhitehead/Nathan-s-JS-Lessons#3]
Interactive lessons are not working because jslint seems to be broken. I have made some changes and I have also made a pull request fixing that.

**Comment by gabrielperales** [comment]
@nwhitehead Hi again Nathan, I came to your lessons again because I thought about doing something similar but for ReasonML. I recently check that these lessons are not online anymore because _app engine_ is not supporting that version of python anymore. Would you mind if I update the code to run on `nodejs` and if I deploy it to any `node` compatible hosting? 

Also, I saw that [nathansuniversity](http://nathansuniversity.com/) seems like is a spam page or something like that. Would you mind to release the content of that course? It was a fantastic course, and I think it is a pity to lose it.

**Comment by nwhitehead** [comment]
@gabrielperales Go for it, update and deploy away.

Ack, thanks for the heads up. No idea what is happening to the site, that is really disturbing. I'll try to get it fixed.
